version: '3'

services:
  rst_api:
    build:
      context: ./rst
      dockerfile: Dockerfile
    container_name: rst_api
    ports:
      - "5000:80"
    tty: true
  aspect_extractor_api:
    build:
      context: ./aspect_extraction
      dockerfile: Dockerfile
    container_name: aspect_extraction_api
    ports:
      - "5001:80"
    tty: true
  sentiment_api:
    build:
      context: ./sentiment
      dockerfile: Dockerfile
    container_name: sentiment_api
    ports:
      - "5002:80"
    tty: true